### ISSUE TITLE
Unnecessary rerender/readding for existing messages

### ISSUE THREAD

**Issue by LKay** [gor181/react-notification-system-redux#17]
In this fragment you remove all notifications that are no longer in the state, which is totally fine.
```javascript
    // Get all active notifications from react-notification-system
    /// and remove all where uid is not found in the reducer
    (this.system().state.notifications || []).forEach(notification => {
      if (notificationIds.indexOf(notification.uid) < 0) {
        this.system().removeNotification(notification.uid);
      }
    });
```

But here you are looping for each notifications in the redux state even if some are already displayed. You should filter the redux notifications against notification that are already displayed and add only new ones.
```javascript
    notifications.forEach(notification => {
      this.system().addNotification({
        ...notification,
        onRemove: () => {
          this.context.store.dispatch(actions.hide(notification.uid));
          notification.onRemove && notification.onRemove();
        }
      });
    });
```

**Comment by gor181** [comment]
Hey @LKay ,

Good spot. Will check on how to solve this soon.

**Comment by gor181** [comment]
Hey @LKay ,

I think this was done on purpose considering react-notification-system is ignoring notifications with same id anyways so we do not need to filter here.

*uid*
```
Overrides the internal uid. Useful if you are managing your notifications id. Notifications with same uid won't be displayed.
```

Let me know if you are seeing duplicates being added which shouldn't be the case.

**Comment by gor181** [comment]
Hey @LKay 

I'm closing this one as I have added tests which are confirming that no additional notifications are being added.

thanks!
