### ISSUE TITLE
[Question] about using the came uid

### ISSUE THREAD

**Issue by nealoke** [gor181/react-notification-system-redux#24]
Hi, I was wondering if you could do something like below. When I use the code now it only renders the first one but ignores the success notification. The idea is to inform the user that we are waiting for a response, and when it finishes update the notification to a success notification. 

Or am I doing this wrong and is there another way to do this?

```
this.props.dispatch(Notifications.info({
	uid: 'propertySettings',
	title: 'Saving property settings'
}));

// if API returns with data
// Update the previous info notification to a success
this.props.dispatch(Notifications.success({
	uid: 'propertySettings',
	title: 'Property settings saved'
}));
```

Ofcourse I can use the `Notifications.hide()` but still feel that this would be nice to have (eg. cleaner)

**Comment by gor181** [comment]
Hey @nealoke ,

Unfortunately react-notification-system itself doesn't support updating already displayed notifications, if that is what you are after.

There is a [issue](https://github.com/igorprado/react-notification-system/issues/33) in the project repo which describes a feature which sounds like yours.

**Comment by nealoke** [comment]
@gor181 indeed saw it as well, thanks!
