### ISSUE TITLE
Cannot clear notification

### ISSUE THREAD

**Issue by Tonvengo** [gor181/react-notification-system-redux#28]
Hi. Is it possible to clear all notifications?
In react-notification-system-redux there is function clearNotifications, could not find similar here.

**Comment by gor181** [comment]
Hi @Tonvengo,

Apologies for delayed reply. No there is no such possibility (yet). But I'll make it happen soon.

**Comment by gor181** [comment]
Hi @Tonvengo,

The feature has been added please check the [documentation](https://github.com/gor181/react-notification-system-redux/tree/1.1.0#actions) or [example](https://github.com/gor181/react-notification-system-redux/blob/master/example/src/components/container.js#L42)

thank you

**Comment by Tonvengo** [comment]
Thanks @gor181!

**Comment by Tonvengo** [comment]
@gor181 I installed latest version of package using npm and when I tried to use removeAll, then same way I used another action creators, I got the following error:
`Uncaught (in promise) TypeError: _reactNotificationSystemRedux2.default.removeAll is not a function`.

I noticed that code uses actions.js file from lib folder. I checked actions.js file in that folder and it doesn't exports function removeAll.
As I can see, it gulp doesn't build this action.js file from src

**Comment by gor181** [comment]
Hi @Tonvengo ,

Yah you are right, I forgot to build before pushing to npm...
That happens when you do not release much 😃 

Anyways, please try getting the most recent one from npm, which should be `1.1.1` and it should export properly.

thank you for reporting,
Goran

**Comment by Tonvengo** [comment]
Hi again @gor181 ,
Thanks. :smiley:
Btw, if you are planning to add any new functionality, just let me know. I would like to collaborate :wink:

**Comment by gor181** [comment]
Np, if you see anything which would be beneficial you are more than welcome 👍  🍻
