### ISSUE TITLE
Document possible functions

### ISSUE THREAD

**Issue by qoalu** [gor181/react-notification-system-redux#30]
Document possible functions for using this plugin

`
Notifications.show(opts = {}, level = 'success')

Notifications.success(opts) 

Notifications.error(opts)

Notifications.warning(opts)

Notifications.info(opts)

Notifications.hide(uid)
`

Had to dig into the source to understand how to send other types of notifications since .show is not in the example

**Comment by gor181** [comment]
Thanks @qoalu for reporting . This is going to be sorted in #33. [link to change](https://github.com/gor181/react-notification-system-redux/pull/33/files).

Closing asap #33 is merged.

**Comment by gor181** [comment]
Hey @qoalu,

Closing, [documented actions](https://github.com/gor181/react-notification-system-redux/tree/1.1.0#actions).

thank you
