### ISSUE TITLE
How to hide all notifications?

### ISSUE THREAD

**Issue by ga12ru12** [gor181/react-notification-system-redux#32]
I used ur system and it's so great. I've read ur source code and i saw function `hide` but i don't know how to hide all notification. Can you help me please? Thanks

**Comment by gor181** [comment]
Hi @ga12ru12,

I have just merged a PR which documents this. Please refer to https://github.com/gor181/react-notification-system-redux/tree/1.1.0#actions.

The one you need is `Notifications.hide(uid)` or `Notifications.removeAll()`.

Do let me know if you need further help.

Thank you,

**Comment by gor181** [comment]
Closing, please reopen if needed.
