### ISSUE TITLE
API Improvement

### ISSUE THREAD

**Issue by Matthijn** [gor181/react-notification-system-redux#36]
Hi. First off, this Notification Center works great. Thanks for making it. 
There's a small API improvement I'd like to suggest though.

Instead of importing the entire `Notifications` object, and calling `.show`, `.info`, ... functions on it. It would be nicer if you could import those functions directly.

So instead of:

```
import Notifications from 'react-notification-system-redux';

dispatch(Notifications.show(notification, level));
dispatch(Notifications.success(notification));
dispatch(Notifications.error(notification));
dispatch(Notifications.warning(notification));
dispatch(Notifications.info(notification));
dispatch(Notifications.hide(uid)); // Hides notification based on uid
dispatch(Notifications.removeAll()); // Removes all notifications
```

You will have:
```
import { show, success, error, warning, info, hide, removeAll } from 'react-notification-system-redux';

dispatch(show(notification, level));
dispatch(success(notification));
dispatch(error(notification));
dispatch(warning(notification));
dispatch(info(notification));
dispatch(hide(uid)); // Hides notification based on uid
dispatch(removeAll()); // Removes all notifications
```

You of course only would have to import the one's you need. And if one of the function names clashes with existing functions (for the importer). They could always do

```
import { show a showNotification } from 'react-notification-system-redux'
```

Or something like that.

Keep up the good work!

**Comment by gor181** [comment]
Yah that is really nice suggestion. Would you have time / will for a PR? Souldn't be much of a change.

**Comment by gor181** [comment]
Hi @Matthijn ,

Are you sure this doesn't already work?
Just created a #41 which adds tests for action exports and seems to work fine. I have also added it to readme.

Thanks,

**Comment by gor181** [comment]
Yah I would think the same, at least now I added tests for that so win-win! Cheers.
