### ISSUE TITLE
Can i edit notification?

### ISSUE THREAD

**Issue by agat** [gor181/react-notification-system-redux#43]
Edit method available in https://github.com/igorprado/react-notification-system

**Comment by gor181** [comment]
Nop you cannot at the moment.
Added this as a feature request.

**Comment by raptox** [comment]
Wow, I would need this badly aswell ...

**Comment by alveshelio** [comment]
Hi @gor181,

First of all, thank you very much for the work you've put into this package, it's an awesome work.

A would badly need this feature too, I don't know what's the state of this feature. 
I'd be willing to help, even though I'm not sure I can be of any help :) not sure my programming skills are up to the task but I'd be glad to help.

Thanks

**Comment by KARTIK01** [comment]
I have created a small demo for edit notification 👉 https://kartik01.github.io/react-notification-system-redux/
Git url 👉 https://github.com/KARTIK01/react-notification-system-redux

@gor181  created PR for the same

**Comment by SheikhG1900** [comment]
please check this demo.  https://codesandbox.io/s/w7rlxrjv65
