### ISSUE TITLE
Update peerDependencies in package.json

### ISSUE THREAD

**Issue by ahaider48** [gor181/react-notification-system-redux#53]
Upon updating to React 16, and running `yarn check` I get the following errors:

```bash
error "react-notification-system-redux#react@^0.14 || ^15.0.0-rc || ^15.0" doesn't satisfy found match of "react@16.0.0"
error "react-notification-system-redux#react-dom@^0.14 || ^15.0.0-rc || ^15.0" doesn't satisfy found match of "react-dom@16.0.0"
```

It would be nice if you can include `react` and `react-dom` 16 in your package.json  peerDependencies as well if possible.

**Comment by ahaider48** [comment]
This issue has been fixed in https://github.com/gor181/react-notification-system-redux/pull/51

**Comment by gor181** [comment]
Updated the PR #51 as tests are failing
