### ISSUE TITLE
`Notifications.hide(uid)` not working

### ISSUE THREAD

**Issue by geminiyellow** [gor181/react-notification-system-redux#6]
https://github.com/gor181/react-notification-system-redux/blob/master/src/actions.js#L42

- this.context.store.dispatch(Notifications.info(opts));
- this.context.store.dispatch(Notifications.hide(opts.uid));

right ? but the toast can not hide.

**Comment by gor181** [comment]
Thanks for reporting @geminiyellow, should be fixed in `1.0.5`

Thanks!!
