### ISSUE TITLE
react-redux v6.x support

### ISSUE THREAD

**Issue by dmitrykrylov** [gor181/react-notification-system-redux#68]
Seems that this line is not compatible with the 6th version of react-redux:

https://github.com/gor181/react-notification-system-redux/blob/d3b53e5abeef231f39afe06247bdf33161fdac7e/src/notifications.js#L33

The component should probably be wrapped into `connect()` HOC.

**Comment by cristianounix** [comment]
This bug are related with this #69 ?

**Comment by dmitrykrylov** [comment]
@cristianounix yes

**Comment by glorp47** [comment]
+1 for this

**Comment by gor181** [comment]
Should be resolved in v2.0.0 which was just released.
Cuddos to @epotockiy
