### ISSUE TITLE
context.store undefined (React 16 + Redux 4)

### ISSUE THREAD

**Issue by cristianounix** [gor181/react-notification-system-redux#69]
<img width="838" alt="screen shot 2018-12-14 at 11 38 27" src="https://user-images.githubusercontent.com/694280/50006441-e78fbe00-ff94-11e8-8c92-7a17364b7093.png">

**Comment by gor181** [comment]
Should be resolved in v2.0.0 which was just released.
Cuddos to @epotockiy
