### ISSUE TITLE
Update Peer Dependencies to support react-redux v7.x

### ISSUE THREAD

**Issue by AlexandreArpin** [gor181/react-notification-system-redux#74]
Hi!

`react-redux` v7.0 released not too long ago and is it should be backward compatible with version v6.0, _unless_ bad assumptions were made about some of the internals of react-redux.

See the note from the [release note of 7.0](https://github.com/reduxjs/react-redux/releases/tag/v7.0.1):
>Note: connect now uses React.memo() internally, which returns a special object rather than a function. Any code that assumed React components are only functions is wrong, and has been wrong since the release of React 16.6. If you were using PropTypes to check for valid component types, you should change from PropTypes.func to PropTypes.elementType instead.

I've been using `react-notification-system-redux` with version 7 of `react-redux` and haven't noticed any errors so far (though my usage is very light). Have you looked into upgrading the peer dependency and are you aware of any breaking changes?

I'd be happy to help submit a PR!

**Comment by AlexandreArpin** [comment]
@gor181 Have you had a chance to look at this?

**Comment by nsaubi** [comment]
@gor181 any update ?

**Comment by Saibamen** [comment]
https://github.com/gor181/react-notification-system-redux/pull/75

**Comment by gor181** [comment]
Released 2.0.1
