### ISSUE TITLE
notifications is undefined in state

### ISSUE THREAD

**Issue by Goldenis** [gor181/react-notification-system-redux#9]
HI @gor181 

```
import {reducer as notifications} from 'react-notification-system-redux'

const App = combineReducers({
	notifications,
})

export default App
```

notification is undefined and unavailable in state.

simple and quite straightfoward issue but I can't find the error.

Thanks.

**Comment by gor181** [comment]
Hey @Goldenis ,

thanks for spotting this one... fixed.

Cheers!
